### DISCUSSION TITLE
Request a help on use access token

### DISCUSSION THREAD

**Discussion by magendirans** [curl/curl#10650] [Q&A]
Hello Folks,

I am creating a simple curl API call to retrieve the access token and use this to in my next steps (call the API functionalities using this access token).

Able to retrieve the access token when I validated using postman call but not in GitHub workflow, It is showing value as "***" and empty string while printing.

Attached here my code,

```
name: Test API Call
 
on:
  workflow_dispatch:
 
jobs:
  run-updater:
    runs-on: self-hosted
    steps:
    # -----------------------------------
    # REST API for get Access Token
    # -----------------------------------
      - name: API Authentication
        run: |
          echo $(curl --location ${{ secrets.UAT_OAUTH_TOKEN_URL }} --header 'Content-Type:application/x-www-form-urlencoded' --data-urlencode 'grant_type=password' --data-urlencode 'client_id=${{ secrets.UAT_OAUTH_CLIENT_ID }}' --data-urlencode 'client_secret=${{ secrets.UAT_OAUTH_CLIENT_SECRET }}' --data-urlencode 'username=${{ secrets.UAT_OAUTH_USERNAME }}' --data-urlencode 'password=${{ secrets.UAT_OAUTH_PASSWORD }}')
        id: get-token

      - name: Print Access Token
        run: echo "Access Token is ${{steps.get-token.outputs.access_token}}"
```

```
API Authentication Output :
{"token_type":"Bearer","expires_in":300,"access_token":"***","refresh_token":"......3c2e457cb31d32e7533389a39cbaefb52d4915cdec5a866a730234201cb8e58b8a86acfdf489657d6751af8a2d09e.........."}

Print Access Token Output :
Access Token is 
```

Kindly assist.
