### DISCUSSION TITLE
Dependencies setup in CI workflows

### DISCUSSION THREAD

**Discussion by bo0tzz** [curl/curl#16970] [General]
Continued from https://fosstodon.org/@bo0tzz/114280857647106700, as I think it's a little more involved than suited for a mastodon thread.

I'm looking at putting together a GHA workflow for the randdisable script (#16962). It looks to me like the main challenge is that it depends on all (or many of?) the ssl/tls libraries. There are already setup steps for those in linux.yml, which I could probably just copy, but I think the tidiest path would be to extract those setup steps into local reusable actions (in `.github/actions`), probably one per dependency, and including the cache handling. Calling those from the workflows could then be as short as
```yaml
      - name: 'build wolfssl (all)'
        if: contains(matrix.build.install_steps, 'wolfssl-all')
        uses: ./.github/actions/setup-wolfssl-all
```
However, this is quite a lot of reorganization and extra files 'just' to run the randdisable script. I can imagine it being useful for other CI workflows down the line, but don't have the context to evaluate whether that would actually be needed.

If I got something wrong or overlooked things, please let me know. If this sounds good, I'm happy to start putting it together.
