### ISSUE TITLE
curl(1) enters busy loop if header size >= 64KB (HTTP2 only)

### ISSUE THREAD

**Issue by kazuho** [curl/curl#659]
curl command seems to enter a busy loop if the size of header becomes greater than 65,534 bytes when HTTP/2 is used.

Steps to reproduce:
1. build [h2o](https://h2o.examp1e.net/) 1.7.0
2. run h2o with following configuration
3. run `curl -k https://127.0.0.1:8081/`

```yaml
listen:
  port: 8081
  ssl:
    key-file: examples/h2o/server.key
    certificate-file: examples/h2o/server.crt
hosts:
  default:
    paths:
      /:
        mruby.handler: |
          Proc.new do |env|
            [200, {"x-foo" => "1" * 65530}, []]
          end
```

The command runs as expected if the size of the header value is 65,529 bytes.

EDIT: I am using curl 7.47.1 with nghttp2 @ 094168a on OS X 10.9.5.
